services:
  app:
    container_name: editmash-app
    build:
      context: .
      target: production-main
      dockerfile: Dockerfile
    ports:
      - "6900:3000"
    env_file:
      - .env
    environment:
      - WS_SERVER_URL=http://editmash-websocket:8080
    depends_on:
      - websocket
    restart: unless-stopped
    networks:
      shared_backend:
        aliases:
          - editmash-app

  websocket:
    container_name: editmash-websocket
    build:
      context: .
      target: production-websocket
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    env_file:
      - websocket/.env
    restart: unless-stopped
    networks:
      shared_backend:
        aliases:
          - editmash-websocket

networks:
  shared_backend:
    external: true
